### ISSUE TITLE
Plugin does not load values on Marlin 1.1.7

### ISSUE THREAD

**Issue by sanderpuh** [amsbr/OctoPrint-EEPROM-Marlin#12]

**Comment by amsbr** [comment]
Hi @sanderpuh,

is it possible send M503 result?

**Comment by sanderpuh** [comment]
Hi @amsbr,

On Octoprint Terminal:
> Send: M503
> Recv: ok

That's all I get.

**Comment by amsbr** [comment]
Hi @sanderpuh,

your EEPROM setting is disabled on firmware compilation. Please confirm this.

**Comment by Wismgari** [comment]
Hi - just had the same issue with 1.1.8. EEPROM can be enabled and the plugin fail if the disable M503 option is used.

Ignore the warning in Marlin to disable M503 for release and the plugin works.

**Comment by amsbr** [comment]
Hi,

yes, the plugin work only with M503 enabled. It uses the M503 result to populate the fields.

**Comment by bcsteeve** [comment]
Man that was frustrating!  I struggled with this for hours before stumbling into here.  PLEASE consider making a check for this sort of thing, and having it suggest in the plugin to check that the necessary lines aren't commented out.  Perhaps also suggest to Marlin folks to make a note in the code documentation (eg. "this is necessary for some plugins, for example the EEPROM-Marlin" or whatever)

**Comment by amsbr** [comment]
Hi @bcsteeve,

good suggestion!

**Comment by amsbr** [comment]
Hi,

added support for all Marlin versions in new release [1.2](https://github.com/amsbr/OctoPrint-EEPROM-Marlin/releases/tag/1.2)
