### ISSUE TITLE
customization 

### ISSUE THREAD

**Issue by jon012198** [amsbr/OctoPrint-EEPROM-Marlin#14]
any we can make it a tab or drop down support like this plugin  https://github.com/xyzaxyz/OctoPrint-Finetunerptr

**Comment by amsbr** [comment]
Hi @jon012198,

feature added to new release [1.2](https://github.com/amsbr/OctoPrint-EEPROM-Marlin/releases/tag/1.2)

**Comment by jon012198** [comment]
![firefox_2018-04-22_10-17-11](https://user-images.githubusercontent.com/7279835/39095930-6ab84eac-4616-11e8-9736-20329a7a380a.png)
![firefox_2018-04-22_10-17-29](https://user-images.githubusercontent.com/7279835/39095932-6ac40454-4616-11e8-83a8-2ef681c050aa.png)
 there is a large gap before the text shows up only on the info tab
@amsbr
