### ISSUE TITLE
Adjust z home position

### ISSUE THREAD

**Issue by shandshellin** [amsbr/OctoPrint-EEPROM-Marlin#16]
IS there a way to enable changing the home position. I can change alot of my Delta settings but if I change the glass for example, and it's a few mm smaller, then i have to connect the printer to laptop, edit marlin, upload, test, etc. I would love to leave this on my octoprint server during these minor calibrations. Perhaps in a future release?

**Comment by amsbr** [comment]
Hi @shandshellin,

please send M503 result here.

Z Offset doesn't work for you?
