### ISSUE TITLE
Problem with new version

### ISSUE THREAD

**Issue by Pajje99** [amsbr/OctoPrint-EEPROM-Marlin#17]
Hi,

I just updatet to your new verison and it seems that it does not handle
HTML right.

I just get the "source" from the form.

![image](https://user-images.githubusercontent.com/16124303/39086586-09f732ea-4594-11e8-8781-07747e809634.png)

**Comment by amsbr** [comment]
Yes, it's a bug. I'm working on it right now.

**Comment by amsbr** [comment]
fixed in 1.2.1
