### ISSUE TITLE
Need updates for new Marlin

### ISSUE THREAD

**Issue by cfelicio** [amsbr/OctoPrint-EEPROM-Marlin#2]
Hi There,

Marlin is about to release a new version, and this plugin needs to be updated. I made a few changes to accommodate my needs (see https://github.com/cfelicio/OctoPrint-EEPROM-Marlin/commit/128ce1bf50f3447fe4f17f4a104b8c1b7e495ee2), but if you can add those changes on a new release and also check for other parameters that might be useful to have, that would be awesome :-)

Cheers!

**Comment by amsbr** [comment]
Thankyou! I will update on next release.

**Comment by amsbr** [comment]
Hi @cfelicio ,

New release [1.0.1](https://github.com/amsbr/OctoPrint-EEPROM-Marlin/releases/tag/1.0.1) added support for Delta settings and ends top adjustments.
