### ISSUE TITLE
Feature request - Thermal runaway settings

### ISSUE THREAD

**Issue by modem7** [amsbr/OctoPrint-EEPROM-Marlin#22]
Would it be possible to put in the settings for thermal runaway for both bed and hotend at all? 

This would enable us to tweak them as necessary, especially if 1) someone hasn't enabled it and 2) change the values for the feature if so required. 

Thanks!

**Comment by amsbr** [comment]
Hi @modem7,

the thermal runaway is not a parameter of the Marlin EEPROM, when it is implemented in the firmware we can consider it here as well.
