### ISSUE TITLE
Bugfix 1.1.8 not showing full advanced tab

### ISSUE THREAD

**Issue by modem7** [amsbr/OctoPrint-EEPROM-Marlin#25]
Heya, 

Just upgraded to latest Marlin bugfix and I used to get the following:

![6](https://user-images.githubusercontent.com/4349962/41373835-62414df8-6f49-11e8-82fd-a626e97e7751.JPG)

However, I now get this:

![capture2](https://user-images.githubusercontent.com/4349962/41373848-69ec4936-6f49-11e8-9537-c99d09b41917.JPG)

Tried resetting EEPROM and reloading, but still no go

**Comment by kakou-fr** [comment]
same problem
