### ISSUE TITLE
Not Loading Data On SkyNet3D variant of Marlin

### ISSUE THREAD

**Issue by qfixit** [amsbr/OctoPrint-EEPROM-Marlin#28]
I've used this plugin on my printer running SkyNet3D before but after a few months of not using it I've come back to see it no longer loading my printers settings. I don't have any error messages appear on the screen and my "Info" button is greyed-out.

Pringer Info from plugin page:
FIRMWARE_NAME:Marlin V1; Sprinter/grbl mashup for gen6 FIRMWARE_URL:https://github.com/ErikZalm/Marlin/ PROTOCOL_VERSION:1.0 MACHINE_TYPE:SkyNet3D EXTRUDER_COUNT:1 UUID:00000000-0000-0000-0000-000000000000
![image](https://user-images.githubusercontent.com/35208750/42784073-94c05b1e-8913-11e8-82d1-756db192901d.png)

**Comment by amsbr** [comment]
Hi @Quintin9801, the EEPROM feature was enabled on this firmware?

**Comment by qfixit** [comment]
Problem solved , reflagged with latest version of skynet. No worries,
perfectly fine to close the issue
