### ISSUE TITLE
Marlin v1 (below v1.01) missing advanced variables

### ISSUE THREAD

**Issue by jhoffman255** [amsbr/OctoPrint-EEPROM-Marlin#3]
Before this update, I was able to access settings for Jerk and Extruder Retraction from my v1 EEPROM. Looks like you're skipping these GCODE commands below v1.01: M204, M205

Here's the version output and the stored settings from my EEPROM:

`Recv: FIRMWARE_NAME:Marlin V1; Sprinter/grbl mashup for gen6 FIRMWARE_URL:http://www.mendel-parts.com PROTOCOL_VERSION:1.0 MACHINE_TYPE:Mendel EXTRUDER_COUNT:1

Send: M501
Recv: echo:Stored settings retrieved
Recv: echo:Steps per unit:
Recv: echo:  M92 X81.00 Y81.00 Z400.50 E94.30
Recv: echo:Maximum feedrates (mm/s):
Recv: echo:  M203 X450.00 Y450.00 Z5.00 E25.00
Recv: echo:Maximum Acceleration (mm/s2):
Recv: echo:  M201 X3000 Y3000 Z100 E3000
Recv: echo:Acceleration: S=acceleration, T=retract acceleration
Recv: echo:  M204 S1000.00 T800.00
Recv: echo:Advanced variables: S=Min feedrate (mm/s), T=Min travel feedrate (mm/s), B=minimum segment time (ms), X=maximum XY jerk (mm/s),  Z=maximum Z jerk (mm/s),  E=maximum E jerk (mm/s)
Recv: echo:  M205 S0.00 T0.00 B20000 X8.00 Z0.40 E1.00
Recv: echo:Home offset (mm):
Recv: echo:  M206 X0.00 Y0.00 Z0.00
Recv: echo:PID settings:
Recv: echo:   M301 P33.41 I1.47 D189.27
Recv: ok`

**Comment by amsbr** [comment]
Hi @jhoffman255 released [1.0.2](https://github.com/amsbr/OctoPrint-EEPROM-Marlin/releases/tag/1.0.2) with Marlin V1; support.

Thankyou
