### ISSUE TITLE
live editing?

### ISSUE THREAD

**Issue by disco22522** [amsbr/OctoPrint-EEPROM-Marlin#6]
Hello, this isn't really an issue with the plugin, more I'm looking for a little more answers.

Am I able to do a live-edit of the eeprom while it's printing? Like, could I change around accell or mm/s at anytime while it's printing or will it require a restart?

**Comment by Leonas** [comment]
You can change it while its printing. No restart needed.

**Comment by amsbr** [comment]
Hi @disco22522! @Leonas is correct. The plugin uses GCode to read and write values.
