### ISSUE TITLE
Installation of update fails!

### ISSUE THREAD

**Issue by azalanono** [amsbr/OctoPrint-EEPROM-Marlin#8]
I tried to install the update, but it does not work.

This happens:

Octoprint notifies me that a new version 1.0.3 exists.
I click on "install".
The install process runs without any error, then octoprint is rebooted.

After re-connecting to octoprint, I get again the notification that a new version 1.0.3 is available. The existing version is (still) 1.0.2.

**Comment by amsbr** [comment]
Hi @azalanono,

An incorrect cached version caused the problem. Try update for new release [1.0.4](https://github.com/amsbr/OctoPrint-EEPROM-Marlin/releases/tag/1.0.4).
